version: "3.9"

services:
  web:
    build:
      context: .
      shm_size: '2gb'
    container_name: post_service_app
    restart: alwayse
    ports:
      - "56567:56567"
    volumes:
      - ./post_service.js:/usr/src/app/post_service.js
    shm_size: '2gb'
